# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: '$(imageName)'

steps:
- script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  displayName: 'Install Rust toolchain'
  condition: ne( variables['Agent.OS'], 'Windows_NT')

- powershell: |
    Invoke-WebRequest -Uri https://win.rustup.rs/x86_64 -OutFile rustup.exe
    ./rustup.exe -y --default-toolchain stable
  displayName: 'Install Rust toolchain'
  condition: eq( variables['Agent.OS'], 'Windows_NT')  

- script: |
    export PATH=$PATH:$HOME/.cargo/bin
    cargo build --release
  displayName: 'Building project'
  condition: ne( variables['Agent.OS'], 'Windows_NT')

- powershell: |
    $Env:Path += "%UserProfile%/.cargo/bin"
    cargo build --release
  displayName: 'Building project'
  condition: eq( variables['Agent.OS'], 'Windows_NT')  