# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: '$(imageName)'

steps:
- script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  displayName: 'Install Rust toolchain'
  condition: ne( variables['Agent.OS'], 'Windows_NT')

- powershell: |
    Invoke-WebRequest -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" -Uri https://win.rustup.rs/ -OutFile rustup-init.exe
    ./rustup-init.exe -y --default-toolchain stable
  displayName: 'Install Rust toolchain - Windows'
  condition: eq( variables['Agent.OS'], 'Windows_NT')  

- script: |
    export PATH=$PATH:$HOME/.cargo/bin
    cargo build --release
  displayName: 'Building project'
  condition: ne( variables['Agent.OS'], 'Windows_NT')

- script: | 
    set PATH=%PATH%;%USERPROFILE%/.cargo/bin
    cargo build --release
  displayName: 'Building project - Windows'
  condition: eq( variables['Agent.OS'], 'Windows_NT')  