[package]
name = "icc"
version = "0.1.0"
authors = ["Emil H. Clausen (SEQUOIIA) <sequoiia@hummel.yt>"]
edition = "2021"

[[bin]]
name = "icc"
path = "src/bin/icc.rs"

[dependencies]
#seqtf_bootstrap = {registry = "seqtf", version = "0.1.4"}
log = "0.4.6"
pretty_env_logger = "0.3"
pnet = "0.34.0"
pnet_macros_support = "0.34.0"
rand = "0.6.5"
chrono = "0.4.6"
toml = "0.4"
serde_derive = "1.0"
serde = "1.0"
ctrlc = {version = "3.2.5", features = ["termination"]}
[dependencies.rusqlite]
version = "0.16.0"
features = ["bundled"]
